# Generated by Django 3.2.5 on 2021-08-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='my_data',
        ),
    ]
